### ISSUE TITLE
mutually recursive definition

### ISSUE THREAD

**Issue by guenni68** [oasis-tcs/odata-abnf#56]
I believe I have found a mutually recursive definition starting in line 993 of the odata-abnf/abnf/odata-abnf-construction-rules.txt file.

I'm referring to this section:

collectionLiteral     = "Collection(" geoLiteral *( COMMA geoLiteral ) CLOSE
geoLiteral            = collectionLiteral
                      / lineStringLiteral
                      / multiPointLiteral
                      / multiLineStringLiteral
                      / multiPolygonLiteral
                      / pointLiteral
                      / polygonLiteral

the rules collectionLiteral and geoLiteral are referring to each other and introduce and endless loop.

**Comment by ralfhandl** [comment]
Hi Guenther (@guenni68),

according to both
* the [EBNF Notation for WKT](https://github.com/cleder/parsewkt/blob/master/parsewkt/Wkt.ebnf) referenced on [Wikipedia](https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry), and 
* [OData V3, 2.2.2 Abstract Type System](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-odata/61934eae-311a-4af4-b8f8-82c112248651)

a geo collection may contain any kind of geo literal, including geo collections., so this definition is intentionally recursive. It is also unambiguous as each nested geo collection starts with the unique case-insensitive prefix `GeometryCollection(` and is terminated by a `)`.

There was however a bug in the ABNF: the prefix literal was missing the `Geometry` prefix. This is/will be fixed by #57.

Does this address your concern?

Thanks in advance!
